import './globals.scss'
import { Montserrat } from 'next/font/google'
import NavbarTop from '@/Components/Utils/NavbarTop'
import Footer from '@/Components/Utils/Footer'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
    title: 'Micron Test',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={`${inter.className} transition-all`}>
                <NavbarTop />
                {children}
                <Footer />
            </body>
        </html>
    )
}
